constants:
  FRAME_WIDTH : 220.0  # Frame size in simulation units
  FRAME_HEIGHT : 700.0
  FRAME_DISCRETIZATION : 1  # Step size
  SPEED : 2  # Weed movement speed
  ROTATION_ANGLE : 10  # Rotation in degrees
  SCREEN_WIDTH : 1024 # Pixel width of the window
  SCREEN_HEIGHT : 3072  # Pixel height of the window
  FONT_SIZE : 16
  TIMER_PERIOD :
    VELOCITY_TIMEOUT : 1.05
    POSITION_TIMEOUT : 1.05

